### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by abdulrahman1s** [JairusSW/kati#4]

**Comment by JairusSW** [comment]
@TheMaestro0 , yeah. Probably a good idea
i'll get to this soon :)

**Comment by JairusSW** [comment]
@TheMaestro1s , just added it! :) Let me know if there are any further issues. Also, string parsing just got 2x faster. I figured out that a bitshift is faster than a bitwise or. Swapped them out, and it got a large performance boost! :)
